portfolio/base/urls.py
from django.urls import path
from . import views
app_name = 'base' 

urlpatterns = [
    path ('', views.home, name='home'),
    path ('cms/', views.cms, name='cms'),

    #POST REQUEST ENDPOINTS
    path ('personalprofile/', views.personalprofile, name='personalprofile'),
    path ('aboutme/', views.aboutme, name='aboutme'),
    path ('socialmedia/', views.socialmedia, name='socialmedia'),

    #PROJECTS
    path ('project/', views.project, name='project'),
    path ('updateproject/', views.updateproject, name='updateproject'),
    path ('deleteproject/', views.deleteproject, name='deleteproject'),

]

portfolio/cms/urls.py
from django.urls import path
from .views import *

app_name = "cms"

urlpatterns = [
    path('login/', signin, name="signin"),
    path('logout/', signout, name="signout"),
    path('changepass/', changepass, name="changepass"),


]

portfolio/portfolio/urls.py
from django.contrib import admin
from django.urls import path, include, reverse
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('',include('base.urls')),
    path('admin/', admin.site.urls),
    path('auth/', include('cms.urls')),

]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

portfolio/cms/models.py
from django.db import models

# Create your models here.

portfolio/cms/views.py
from django.shortcuts import render, redirect, reverse
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required

# Create your views here.

def signin(request):
    if request.method == "POST":
        username = request.POST["username"]
        password = request.POST["password"]
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect(reverse("base:cms"))
        else:
            print("cant login")
            
    return render(request, 'signin.html')

@login_required(login_url="/auth/login/")
def signout(request):
    logout(request)  
    return redirect(reverse("base:home"))

@login_required(login_url="/auth/login/")
def changepass(request):  

    if request.method == "POST":
        user = request.user
        password = request.POST.get("password", user.password)
        user.set_password()
        user.save()
    return redirect(reverse("base:cms"))

portfolio/templates/cms.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>John Vincent Obispo</title>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <link href="https://fonts.googleapis.com/css2?family=Open+Sans:wght@300;400;600&display=swap" rel="stylesheet">
    <link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link rel="preconnect" href="https://fonts.googleapis.com">
<link href="https://fonts.googleapis.com/css2?family=Poppins:wght@400;500;600&family=Montserrat:wght@400;500;600&display=swap" rel="stylesheet">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">
<link href="https://unpkg.com/aos@2.3.1/dist/aos.css" rel="stylesheet">
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">


<link rel = "stylesheet" href = "{% static 'style.css' %}">
<link href="static/style.css" rel="stylesheet">
  

<style>
  
  
  .navbar {
  box-shadow: 0px 2px 5px rgba(0, 0, 0, 0.1);
  padding: 10px 20px;
}

.menu-icon {
  font-size: 24px;
  cursor: pointer;
}

.sidenav {
  height: 100%;
  width: 0;
  position: fixed;
  z-index: 1000;
  top: 0;
  left: 0;
  background-color: #ffffff;
  overflow-x: hidden;
  padding-top: 60px;
  transition: 0.5s;
  box-shadow: 2px 0px 5px rgba(0, 0, 0, 0.1);
}

.sidenav a {
  padding: 15px 20px;
  text-decoration: none;
  font-size: 18px;
  color: #333333;
  display: block;
  transition: 0.3s;
}

.sidenav a:hover {
  background-color: #f5f5f5;
}

.sidenav .closebtn {
  position: absolute;
  top: 10px;
  right: 10px;
  font-size: 24px;
}

#main {
  transition: margin-left 0.5s;
  padding: 20px;
}

  </style>
</head>

<body class="cms-body">
            <!-- Sidebar -->
            <div class="navbar">
              <span class="menu-icon" style="color: white;" onclick="openNav()">&#9776;</span>
            </div>
            
            <div id="mySidenav" class="sidenav">
              <a href="javascript:void(0)" class="closebtn" onclick="closeNav()">&times;</a>
              <a href="#">About</a>
              <a href="#">Exhibit Content</a>
              <a href="#">Social Media</a>
            </div>
      

    <!-- about me form -->
    <div class="admin-container" >
      <div class="card p-4 shadow rounded-3" style="width: 100%;">
        <form action="{% url 'base:aboutme' %}" method="POST" enctype="multipart/form-data">
          {% csrf_token %}
          <div class="text-center mb-4">
            <h2 class="fw-bold mb-0">About Me Form</h2>
            <p class="text-muted">Brief description and summary of the resume</p>
          </div>
    
          <div class="form-group mb-4">
            <label for="address" class="form-label">Address:</label>
            <input type="text" class="form-control rounded-3" id="address" name="address">
          </div>
    
          <div class="form-group mb-4">
            <label for="email" class="form-label">Email:</label>
            <input type="email" class="form-control rounded-3" id="email" name="email">
          </div>
    
          <div class="form-group mb-4">
            <label for="number" class="form-label">Number:</label>
            <input type="text" class="form-control rounded-3" id="number" name="contact_number">
          </div>

          <div class="form-group mb-4">
            <label for="greeting_description" class="form-label">Description:</label>
            <textarea class="form-control rounded-3" id="greeting_description" name="greeting_description" rows="5">{{user_data.greeting_description}}</textarea>
          </div>
    
          <div class="form-group mb-4">
            <label for="about_photo" class="form-label">Upload Photo:</label>
            <input type="file" class="form-control-file" id="about_photo" name="about_photo">
          </div>
    
          <div class="d-grid gap-2">
            <button type="submit" class="btn btn-primary rounded-pill">Submit</button>
            <button type="button" class="btn btn-outline-secondary rounded-pill">Update</button>
          </div>
        </form>
      </div>
    </div>
    

         <!-- EXHIBIT form -->
         <div class="admin-container">
          <div class="card p-4 shadow rounded-3">
            <form action="{% url 'base:project' %}" method="POST" enctype="multipart/form-data">
              {% csrf_token %}
              <div class="text-center mb-4">
                <h2 class="fw-bold mb-0">Exhibit Form</h2>
                <p class="text-muted">Add new projects or update existing ones</p>
              </div>
        
              <div class="form-group mb-4">
                <label for="showcase_title" class="form-label">Showcase Title:</label>
                <textarea class="form-control rounded-3" id="showcase_title" name="showcase_title" rows="3"></textarea>
              </div>
        
              <div class="form-group mb-4">
                <label for="showcase_description" class="form-label">Showcase Description:</label>
                <textarea class="form-control rounded-3" id="showcase_description" name="showcase_description" rows="3"></textarea>
              </div>
        
              <div class="form-group mb-4">
                <label for="project_images" class="form-label">Upload Photo:</label>

                <input type="file" multiple class="form-control-file" id="project_photo" name="project_images">
              </div>
        
              <button type="submit" class="btn btn-primary rounded-pill mb-3">Submit</button>
            </form>
        
            <div class="table-container">
            <table class="table table-hover">
              <thead>
                <tr>
                  <th scope="col">Showcase Title</th>
                  <th scope="col">Actions</th>
                </tr>
              </thead>
              <tbody>
                {% for project in user_data.user_project.all %}
                <tr>
                  <td>{{ project.showcase_title }}</td>
                  <td>
                    <button type="button" class="btn btn-success btn-sm" data-toggle="modal" data-target="#modal{{ project.id }}">Update</button>
                    <button type="button" class="btn btn-danger btn-sm" data-toggle="modal" data-target="#confirmmodal{{ project.id }}">Delete</button>
                  </td>
                </tr>

<!-- Modal update -->
<div class="modal fade" id="modal{{project.id}}" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Modal title</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <form action="{% url 'base:updateproject' %}" method="POST" enctype="multipart/form-data">
          {% csrf_token %}
            <div class="form-group">
              <h2>Project Form</h2>
          
            </div>
            <div class="form-group">
              <label for="showcase_title{{project.id}}">Showcase Title:</label>
              <textarea class="form-control" id="showcase_title{{project.id}}" name="showcase_title" rows="5"></textarea>
            </div>
            <div class="form-group">
              <label for="showcase_description{{project.id}}">Showcase Description:</label>
              <textarea class="form-control" id="showcase_description{{project.id}}" name="showcase_description" rows="5"></textarea>
            </div>
            <div class="form-group">
              <label for="photo{{project.id}}">Upload Photo:</label>
              <input type="file" multiple class="form-control-file" id="photo{{project.id}}" name="project_images">
            </div>
            <input type="text" value="{{project.id}}" name="project_id" class="d-none">
            <button type="submit" class="btn btn-primary">Submit</button>
        </form>
      </div>
    </div>
  </div>
</div>


<!-- Modal delete -->
<div class="modal fade" id="confirmmodal{{project.id}}" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Modal title</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
        
      </div>
      <div class="modal-body">
      <p>Are you sure you want to delete this project?</p>
      </div>
      <div class="modal-footer">
        <form action="{% url 'base:deleteproject' %}" method="POST" enctype="multipart/form-data">
          {% csrf_token %}
          <input type="text" value="{{project.id}}" name="project_id" class="d-none">

        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <button type="submit" class="btn btn-danger">Delete</button>
        </form>
      </div>
    </div>
  </div>
</div>
              {% endfor %}
           </tbody>
    </table>
            </div>
  </div>
</div>
      
      <!-- socmeds -->
      <div class="admin-container" >
        <div class="card p-4 shadow rounded-3" style="width: 100%;">
          <div class="text-center mb-4">
            <h2 class="fw-bold mb-0">Social Media Form</h2>
            <p class="text-muted">Dynamic Links for future references.</p>
          </div>
    
            <form action="{% url 'base:socialmedia' %}" method="POST">
                {% csrf_token %}
              
                <div class="form-group mb-4">
                    <label for="facebook_link">Facebook:</label>
                    <input type="text" class="form-control" id="facebook_link" name="facebook_link">
                </div>
                <div class="form-group mb-4">
                    <label for="github_link">Github:</label>
                    <input type="text" class="form-control" id="github_link" name="github_link">
                </div>
                <div class="form-group mb-4">
                    <label for="linkedin_link">Linkedin:</label>
                    <input type="text" class="form-control" id="linkedin_link" name="linkedin_link">
                </div>
                <div class="form-group mb-4">
                    <label for="discord_link">Discord:</label>
                    <input type="text" class="form-control" id="discord_link" name="discord_link">
                </div>
                <button type="submit" class="btn btn-primary">Submit</button>
                <button type="button" class="btn btn-secondary">Update</button>
            </form>
        </div>
    </div>
    


      
<script>
function openNav() {
  document.getElementById("mySidenav").style.width = "250px";
  document.getElementById("main").style.marginLeft = "250px";
}

function closeNav() {
  document.getElementById("mySidenav").style.width = "0";
  document.getElementById("main").style.marginLeft = "0";
}

</script>

    <script async src="https://tenor.com/embed.js"></script>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js"></script>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.9.5/dist/umd/popper.min.js"></script>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>
</body>
</html>

portfolio/templates/signin.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Sign In</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <link href="https://fonts.googleapis.com/css2?family=Open+Sans:wght@300;400;600&display=swap" rel="stylesheet">
    <link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link rel="preconnect" href="https://fonts.googleapis.com">
<link href="https://fonts.googleapis.com/css2?family=Poppins:wght@400;500;600&family=Montserrat:wght@400;500;600&display=swap" rel="stylesheet">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">
<link href="https://unpkg.com/aos@2.3.1/dist/aos.css" rel="stylesheet">
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">


</head>

<body>

  <div class="container d-flex justify-content-center align-items-center" style="height: 100vh;">
    <div class="card p-4">
      <form method="POST" action="{% url 'cms:signin' %}">
        {% csrf_token %}
        <div class="form-group mb-4">
          <label for="username" class="form-label">Username</label>
          <input type="text" id="username" name="username" class="form-control" />
        </div>
  
        <div class="form-group mb-4">
          <label for="password" class="form-label">Password</label>
          <input type="password" id="password" name="password" class="form-control" />
        </div>
  
        <div class="form-check mb-4">
          <input class="form-check-input" type="checkbox" id="rememberMe" checked />
          <label class="form-check-label" for="rememberMe"> Remember me </label>
        </div>
  
        <button type="submit" class="btn btn-primary btn-block">Login</button>
      </form>
    </div>
  </div>
  


    <script async src="https://tenor.com/embed.js"></script>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.9.5/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</body>
</html>